// flow-typed signature: 22167da581bbbced2845496c92a9bb4a
// flow-typed version: <<STUB>>/eslint-config-dslemay_v^1.0.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-dslemay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-dslemay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-dslemay/best-practices' {
  declare module.exports: any;
}

declare module 'eslint-config-dslemay/es6' {
  declare module.exports: any;
}

declare module 'eslint-config-dslemay/import' {
  declare module.exports: any;
}

declare module 'eslint-config-dslemay/jest' {
  declare module.exports: any;
}

declare module 'eslint-config-dslemay/jsx-a11y' {
  declare module.exports: any;
}

declare module 'eslint-config-dslemay/possible-errors' {
  declare module.exports: any;
}

declare module 'eslint-config-dslemay/react' {
  declare module.exports: any;
}

declare module 'eslint-config-dslemay/stylistic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-dslemay/best-practices.js' {
  declare module.exports: $Exports<'eslint-config-dslemay/best-practices'>;
}
declare module 'eslint-config-dslemay/es6.js' {
  declare module.exports: $Exports<'eslint-config-dslemay/es6'>;
}
declare module 'eslint-config-dslemay/import.js' {
  declare module.exports: $Exports<'eslint-config-dslemay/import'>;
}
declare module 'eslint-config-dslemay/index' {
  declare module.exports: $Exports<'eslint-config-dslemay'>;
}
declare module 'eslint-config-dslemay/index.js' {
  declare module.exports: $Exports<'eslint-config-dslemay'>;
}
declare module 'eslint-config-dslemay/jest.js' {
  declare module.exports: $Exports<'eslint-config-dslemay/jest'>;
}
declare module 'eslint-config-dslemay/jsx-a11y.js' {
  declare module.exports: $Exports<'eslint-config-dslemay/jsx-a11y'>;
}
declare module 'eslint-config-dslemay/possible-errors.js' {
  declare module.exports: $Exports<'eslint-config-dslemay/possible-errors'>;
}
declare module 'eslint-config-dslemay/react.js' {
  declare module.exports: $Exports<'eslint-config-dslemay/react'>;
}
declare module 'eslint-config-dslemay/stylistic.js' {
  declare module.exports: $Exports<'eslint-config-dslemay/stylistic'>;
}
