// flow-typed signature: 86a1e6f0b274c34c2daf3bec49944f17
// flow-typed version: <<STUB>>/gatsby-theme-dslemay-core_v^0.3.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-theme-dslemay-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-theme-dslemay-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-theme-dslemay-core/gatsby-config' {
  declare module.exports: any;
}

declare module 'gatsby-theme-dslemay-core/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-theme-dslemay-core/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-theme-dslemay-core/gatsby-config.js' {
  declare module.exports: $Exports<'gatsby-theme-dslemay-core/gatsby-config'>;
}
declare module 'gatsby-theme-dslemay-core/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-theme-dslemay-core/gatsby-node'>;
}
declare module 'gatsby-theme-dslemay-core/index' {
  declare module.exports: $Exports<'gatsby-theme-dslemay-core'>;
}
declare module 'gatsby-theme-dslemay-core/index.js' {
  declare module.exports: $Exports<'gatsby-theme-dslemay-core'>;
}
declare module 'gatsby-theme-dslemay-core/utils.js' {
  declare module.exports: $Exports<'gatsby-theme-dslemay-core/utils'>;
}
