// flow-typed signature: c57c3e7861f787395311159b694c7eb5
// flow-typed version: <<STUB>>/gatsby-plugin-emotion_vnext/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-emotion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-emotion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-emotion/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-emotion/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-emotion/gatsby-ssr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-emotion/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-emotion/gatsby-browser'>;
}
declare module 'gatsby-plugin-emotion/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-emotion/gatsby-node'>;
}
declare module 'gatsby-plugin-emotion/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-emotion/gatsby-ssr'>;
}
declare module 'gatsby-plugin-emotion/index' {
  declare module.exports: $Exports<'gatsby-plugin-emotion'>;
}
declare module 'gatsby-plugin-emotion/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-emotion'>;
}
