// flow-typed signature: 2e240aed81fdd50077d07f001c58e8f7
// flow-typed version: <<STUB>>/gatsby-remark-prismjs_v^3.0.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-remark-prismjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-remark-prismjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-remark-prismjs/add-line-numbers' {
  declare module.exports: any;
}

declare module 'gatsby-remark-prismjs/command-line' {
  declare module.exports: any;
}

declare module 'gatsby-remark-prismjs/directives' {
  declare module.exports: any;
}

declare module 'gatsby-remark-prismjs/highlight-code' {
  declare module.exports: any;
}

declare module 'gatsby-remark-prismjs/load-prism-language-extension' {
  declare module.exports: any;
}

declare module 'gatsby-remark-prismjs/load-prism-language' {
  declare module.exports: any;
}

declare module 'gatsby-remark-prismjs/parse-options' {
  declare module.exports: any;
}

declare module 'gatsby-remark-prismjs/replace-string-with-regexp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-remark-prismjs/add-line-numbers.js' {
  declare module.exports: $Exports<'gatsby-remark-prismjs/add-line-numbers'>;
}
declare module 'gatsby-remark-prismjs/command-line.js' {
  declare module.exports: $Exports<'gatsby-remark-prismjs/command-line'>;
}
declare module 'gatsby-remark-prismjs/directives.js' {
  declare module.exports: $Exports<'gatsby-remark-prismjs/directives'>;
}
declare module 'gatsby-remark-prismjs/highlight-code.js' {
  declare module.exports: $Exports<'gatsby-remark-prismjs/highlight-code'>;
}
declare module 'gatsby-remark-prismjs/index' {
  declare module.exports: $Exports<'gatsby-remark-prismjs'>;
}
declare module 'gatsby-remark-prismjs/index.js' {
  declare module.exports: $Exports<'gatsby-remark-prismjs'>;
}
declare module 'gatsby-remark-prismjs/load-prism-language-extension.js' {
  declare module.exports: $Exports<'gatsby-remark-prismjs/load-prism-language-extension'>;
}
declare module 'gatsby-remark-prismjs/load-prism-language.js' {
  declare module.exports: $Exports<'gatsby-remark-prismjs/load-prism-language'>;
}
declare module 'gatsby-remark-prismjs/parse-options.js' {
  declare module.exports: $Exports<'gatsby-remark-prismjs/parse-options'>;
}
declare module 'gatsby-remark-prismjs/replace-string-with-regexp.js' {
  declare module.exports: $Exports<'gatsby-remark-prismjs/replace-string-with-regexp'>;
}
