// flow-typed signature: bd49ba17178dc15bd8a08d7358934b73
// flow-typed version: <<STUB>>/gatsby-theme-dslemay-core_v^0.2.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-theme-dslemay-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-theme-dslemay-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-theme-dslemay-core/__tests__/gatsby-config.test' {
  declare module.exports: any;
}

declare module 'gatsby-theme-dslemay-core/__tests__/gatsby-node.test' {
  declare module.exports: any;
}

declare module 'gatsby-theme-dslemay-core/__tests__/plugin-testing.test' {
  declare module.exports: any;
}

declare module 'gatsby-theme-dslemay-core/gatsby-config' {
  declare module.exports: any;
}

declare module 'gatsby-theme-dslemay-core/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-theme-dslemay-core/plugin-testing' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-theme-dslemay-core/__tests__/gatsby-config.test.js' {
  declare module.exports: $Exports<'gatsby-theme-dslemay-core/__tests__/gatsby-config.test'>;
}
declare module 'gatsby-theme-dslemay-core/__tests__/gatsby-node.test.js' {
  declare module.exports: $Exports<'gatsby-theme-dslemay-core/__tests__/gatsby-node.test'>;
}
declare module 'gatsby-theme-dslemay-core/__tests__/plugin-testing.test.js' {
  declare module.exports: $Exports<'gatsby-theme-dslemay-core/__tests__/plugin-testing.test'>;
}
declare module 'gatsby-theme-dslemay-core/gatsby-config.js' {
  declare module.exports: $Exports<'gatsby-theme-dslemay-core/gatsby-config'>;
}
declare module 'gatsby-theme-dslemay-core/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-theme-dslemay-core/gatsby-node'>;
}
declare module 'gatsby-theme-dslemay-core/index' {
  declare module.exports: $Exports<'gatsby-theme-dslemay-core'>;
}
declare module 'gatsby-theme-dslemay-core/index.js' {
  declare module.exports: $Exports<'gatsby-theme-dslemay-core'>;
}
declare module 'gatsby-theme-dslemay-core/plugin-testing.js' {
  declare module.exports: $Exports<'gatsby-theme-dslemay-core/plugin-testing'>;
}
