// flow-typed signature: d7934cc495d1ab4d2b81a0ace41b8a0c
// flow-typed version: <<STUB>>/gatsby-remark-prismjs_vnext/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-remark-prismjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-remark-prismjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-remark-prismjs/add-line-numbers' {
  declare module.exports: any;
}

declare module 'gatsby-remark-prismjs/highlight-code' {
  declare module.exports: any;
}

declare module 'gatsby-remark-prismjs/load-prism-language' {
  declare module.exports: any;
}

declare module 'gatsby-remark-prismjs/parse-line-number-range' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-remark-prismjs/add-line-numbers.js' {
  declare module.exports: $Exports<'gatsby-remark-prismjs/add-line-numbers'>;
}
declare module 'gatsby-remark-prismjs/highlight-code.js' {
  declare module.exports: $Exports<'gatsby-remark-prismjs/highlight-code'>;
}
declare module 'gatsby-remark-prismjs/index' {
  declare module.exports: $Exports<'gatsby-remark-prismjs'>;
}
declare module 'gatsby-remark-prismjs/index.js' {
  declare module.exports: $Exports<'gatsby-remark-prismjs'>;
}
declare module 'gatsby-remark-prismjs/load-prism-language.js' {
  declare module.exports: $Exports<'gatsby-remark-prismjs/load-prism-language'>;
}
declare module 'gatsby-remark-prismjs/parse-line-number-range.js' {
  declare module.exports: $Exports<'gatsby-remark-prismjs/parse-line-number-range'>;
}
