// flow-typed signature: 710cb7080b29795555c8a8a3f9d90b0d
// flow-typed version: <<STUB>>/gatsby-source-contentful_v^2.0.35/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-source-contentful'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-source-contentful' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-source-contentful/cache-image' {
  declare module.exports: any;
}

declare module 'gatsby-source-contentful/download-contentful-assets' {
  declare module.exports: any;
}

declare module 'gatsby-source-contentful/extend-node-type' {
  declare module.exports: any;
}

declare module 'gatsby-source-contentful/fetch' {
  declare module.exports: any;
}

declare module 'gatsby-source-contentful/fragments' {
  declare module.exports: any;
}

declare module 'gatsby-source-contentful/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-source-contentful/normalize' {
  declare module.exports: any;
}

declare module 'gatsby-source-contentful/schemes' {
  declare module.exports: any;
}

declare module 'gatsby-source-contentful/scripts/download-data' {
  declare module.exports: any;
}

declare module 'gatsby-source-contentful/src/cache-image' {
  declare module.exports: any;
}

declare module 'gatsby-source-contentful/src/download-contentful-assets' {
  declare module.exports: any;
}

declare module 'gatsby-source-contentful/src/extend-node-type' {
  declare module.exports: any;
}

declare module 'gatsby-source-contentful/src/fetch' {
  declare module.exports: any;
}

declare module 'gatsby-source-contentful/src/fragments' {
  declare module.exports: any;
}

declare module 'gatsby-source-contentful/src/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-source-contentful/src/normalize' {
  declare module.exports: any;
}

declare module 'gatsby-source-contentful/src/schemes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-source-contentful/cache-image.js' {
  declare module.exports: $Exports<'gatsby-source-contentful/cache-image'>;
}
declare module 'gatsby-source-contentful/download-contentful-assets.js' {
  declare module.exports: $Exports<'gatsby-source-contentful/download-contentful-assets'>;
}
declare module 'gatsby-source-contentful/extend-node-type.js' {
  declare module.exports: $Exports<'gatsby-source-contentful/extend-node-type'>;
}
declare module 'gatsby-source-contentful/fetch.js' {
  declare module.exports: $Exports<'gatsby-source-contentful/fetch'>;
}
declare module 'gatsby-source-contentful/fragments.js' {
  declare module.exports: $Exports<'gatsby-source-contentful/fragments'>;
}
declare module 'gatsby-source-contentful/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-source-contentful/gatsby-node'>;
}
declare module 'gatsby-source-contentful/index' {
  declare module.exports: $Exports<'gatsby-source-contentful'>;
}
declare module 'gatsby-source-contentful/index.js' {
  declare module.exports: $Exports<'gatsby-source-contentful'>;
}
declare module 'gatsby-source-contentful/normalize.js' {
  declare module.exports: $Exports<'gatsby-source-contentful/normalize'>;
}
declare module 'gatsby-source-contentful/schemes.js' {
  declare module.exports: $Exports<'gatsby-source-contentful/schemes'>;
}
declare module 'gatsby-source-contentful/scripts/download-data.js' {
  declare module.exports: $Exports<'gatsby-source-contentful/scripts/download-data'>;
}
declare module 'gatsby-source-contentful/src/cache-image.js' {
  declare module.exports: $Exports<'gatsby-source-contentful/src/cache-image'>;
}
declare module 'gatsby-source-contentful/src/download-contentful-assets.js' {
  declare module.exports: $Exports<'gatsby-source-contentful/src/download-contentful-assets'>;
}
declare module 'gatsby-source-contentful/src/extend-node-type.js' {
  declare module.exports: $Exports<'gatsby-source-contentful/src/extend-node-type'>;
}
declare module 'gatsby-source-contentful/src/fetch.js' {
  declare module.exports: $Exports<'gatsby-source-contentful/src/fetch'>;
}
declare module 'gatsby-source-contentful/src/fragments.js' {
  declare module.exports: $Exports<'gatsby-source-contentful/src/fragments'>;
}
declare module 'gatsby-source-contentful/src/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-source-contentful/src/gatsby-node'>;
}
declare module 'gatsby-source-contentful/src/normalize.js' {
  declare module.exports: $Exports<'gatsby-source-contentful/src/normalize'>;
}
declare module 'gatsby-source-contentful/src/schemes.js' {
  declare module.exports: $Exports<'gatsby-source-contentful/src/schemes'>;
}
