// flow-typed signature: 458e21a36e1e07ada8d5906110b80f16
// flow-typed version: <<STUB>>/is-ci-cli_v^1.1.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-ci-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-ci-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'is-ci-cli/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'is-ci-cli/cli.js' {
  declare module.exports: $Exports<'is-ci-cli/cli'>;
}
