// flow-typed signature: 2a158613588a58d78e942853d3227e80
// flow-typed version: <<STUB>>/prettier-config-dslemay_v^1.0.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier-config-dslemay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier-config-dslemay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'prettier-config-dslemay/index' {
  declare module.exports: $Exports<'prettier-config-dslemay'>;
}
declare module 'prettier-config-dslemay/index.js' {
  declare module.exports: $Exports<'prettier-config-dslemay'>;
}
