// flow-typed signature: 01b6faf2f9dafaef497b3a1faf7521ee
// flow-typed version: <<STUB>>/react-icons_v^3.4.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-icons/all' {
  declare module.exports: any;
}

declare module 'react-icons/di/index.esm' {
  declare module.exports: any;
}

declare module 'react-icons/di/index' {
  declare module.exports: any;
}

declare module 'react-icons/fa/index.esm' {
  declare module.exports: any;
}

declare module 'react-icons/fa/index' {
  declare module.exports: any;
}

declare module 'react-icons/fi/index.esm' {
  declare module.exports: any;
}

declare module 'react-icons/fi/index' {
  declare module.exports: any;
}

declare module 'react-icons/gi/index.esm' {
  declare module.exports: any;
}

declare module 'react-icons/gi/index' {
  declare module.exports: any;
}

declare module 'react-icons/go/index.esm' {
  declare module.exports: any;
}

declare module 'react-icons/go/index' {
  declare module.exports: any;
}

declare module 'react-icons/io/index.esm' {
  declare module.exports: any;
}

declare module 'react-icons/io/index' {
  declare module.exports: any;
}

declare module 'react-icons/lib/cjs/iconBase' {
  declare module.exports: any;
}

declare module 'react-icons/lib/cjs/iconContext' {
  declare module.exports: any;
}

declare module 'react-icons/lib/cjs/iconsManifest' {
  declare module.exports: any;
}

declare module 'react-icons/lib/cjs/index' {
  declare module.exports: any;
}

declare module 'react-icons/lib/esm/iconBase' {
  declare module.exports: any;
}

declare module 'react-icons/lib/esm/iconContext' {
  declare module.exports: any;
}

declare module 'react-icons/lib/esm/iconsManifest' {
  declare module.exports: any;
}

declare module 'react-icons/lib/esm/index' {
  declare module.exports: any;
}

declare module 'react-icons/md/index.esm' {
  declare module.exports: any;
}

declare module 'react-icons/md/index' {
  declare module.exports: any;
}

declare module 'react-icons/plugin/defaultImportConverter' {
  declare module.exports: any;
}

declare module 'react-icons/src/icons/index' {
  declare module.exports: any;
}

declare module 'react-icons/ti/index.esm' {
  declare module.exports: any;
}

declare module 'react-icons/ti/index' {
  declare module.exports: any;
}

declare module 'react-icons/wi/index.esm' {
  declare module.exports: any;
}

declare module 'react-icons/wi/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-icons/all.js' {
  declare module.exports: $Exports<'react-icons/all'>;
}
declare module 'react-icons/di/index.esm.js' {
  declare module.exports: $Exports<'react-icons/di/index.esm'>;
}
declare module 'react-icons/di/index.js' {
  declare module.exports: $Exports<'react-icons/di/index'>;
}
declare module 'react-icons/fa/index.esm.js' {
  declare module.exports: $Exports<'react-icons/fa/index.esm'>;
}
declare module 'react-icons/fa/index.js' {
  declare module.exports: $Exports<'react-icons/fa/index'>;
}
declare module 'react-icons/fi/index.esm.js' {
  declare module.exports: $Exports<'react-icons/fi/index.esm'>;
}
declare module 'react-icons/fi/index.js' {
  declare module.exports: $Exports<'react-icons/fi/index'>;
}
declare module 'react-icons/gi/index.esm.js' {
  declare module.exports: $Exports<'react-icons/gi/index.esm'>;
}
declare module 'react-icons/gi/index.js' {
  declare module.exports: $Exports<'react-icons/gi/index'>;
}
declare module 'react-icons/go/index.esm.js' {
  declare module.exports: $Exports<'react-icons/go/index.esm'>;
}
declare module 'react-icons/go/index.js' {
  declare module.exports: $Exports<'react-icons/go/index'>;
}
declare module 'react-icons/io/index.esm.js' {
  declare module.exports: $Exports<'react-icons/io/index.esm'>;
}
declare module 'react-icons/io/index.js' {
  declare module.exports: $Exports<'react-icons/io/index'>;
}
declare module 'react-icons/lib/cjs/iconBase.js' {
  declare module.exports: $Exports<'react-icons/lib/cjs/iconBase'>;
}
declare module 'react-icons/lib/cjs/iconContext.js' {
  declare module.exports: $Exports<'react-icons/lib/cjs/iconContext'>;
}
declare module 'react-icons/lib/cjs/iconsManifest.js' {
  declare module.exports: $Exports<'react-icons/lib/cjs/iconsManifest'>;
}
declare module 'react-icons/lib/cjs/index.js' {
  declare module.exports: $Exports<'react-icons/lib/cjs/index'>;
}
declare module 'react-icons/lib/esm/iconBase.js' {
  declare module.exports: $Exports<'react-icons/lib/esm/iconBase'>;
}
declare module 'react-icons/lib/esm/iconContext.js' {
  declare module.exports: $Exports<'react-icons/lib/esm/iconContext'>;
}
declare module 'react-icons/lib/esm/iconsManifest.js' {
  declare module.exports: $Exports<'react-icons/lib/esm/iconsManifest'>;
}
declare module 'react-icons/lib/esm/index.js' {
  declare module.exports: $Exports<'react-icons/lib/esm/index'>;
}
declare module 'react-icons/md/index.esm.js' {
  declare module.exports: $Exports<'react-icons/md/index.esm'>;
}
declare module 'react-icons/md/index.js' {
  declare module.exports: $Exports<'react-icons/md/index'>;
}
declare module 'react-icons/plugin/defaultImportConverter.js' {
  declare module.exports: $Exports<'react-icons/plugin/defaultImportConverter'>;
}
declare module 'react-icons/src/icons/index.js' {
  declare module.exports: $Exports<'react-icons/src/icons/index'>;
}
declare module 'react-icons/ti/index.esm.js' {
  declare module.exports: $Exports<'react-icons/ti/index.esm'>;
}
declare module 'react-icons/ti/index.js' {
  declare module.exports: $Exports<'react-icons/ti/index'>;
}
declare module 'react-icons/wi/index.esm.js' {
  declare module.exports: $Exports<'react-icons/wi/index.esm'>;
}
declare module 'react-icons/wi/index.js' {
  declare module.exports: $Exports<'react-icons/wi/index'>;
}
