// flow-typed signature: 80dd7e96e4f3866988d1eaafbcc54e9c
// flow-typed version: <<STUB>>/react-typography_v^0.16.13/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-typography'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-typography' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-typography/dist/GoogleFont' {
  declare module.exports: any;
}

declare module 'react-typography/dist/index' {
  declare module.exports: any;
}

declare module 'react-typography/dist/TypographyStyle' {
  declare module.exports: any;
}

declare module 'react-typography/src/GoogleFont' {
  declare module.exports: any;
}

declare module 'react-typography/src/index' {
  declare module.exports: any;
}

declare module 'react-typography/src/TypographyStyle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-typography/dist/GoogleFont.js' {
  declare module.exports: $Exports<'react-typography/dist/GoogleFont'>;
}
declare module 'react-typography/dist/index.js' {
  declare module.exports: $Exports<'react-typography/dist/index'>;
}
declare module 'react-typography/dist/TypographyStyle.js' {
  declare module.exports: $Exports<'react-typography/dist/TypographyStyle'>;
}
declare module 'react-typography/src/GoogleFont.js' {
  declare module.exports: $Exports<'react-typography/src/GoogleFont'>;
}
declare module 'react-typography/src/index.js' {
  declare module.exports: $Exports<'react-typography/src/index'>;
}
declare module 'react-typography/src/TypographyStyle.js' {
  declare module.exports: $Exports<'react-typography/src/TypographyStyle'>;
}
