// flow-typed signature: e3475ad29d8988796c0208374d24cc12
// flow-typed version: <<STUB>>/typography-theme-lincoln_v^0.16.18/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typography-theme-lincoln'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typography-theme-lincoln' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typography-theme-lincoln/dist/index' {
  declare module.exports: any;
}

declare module 'typography-theme-lincoln/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typography-theme-lincoln/dist/index.js' {
  declare module.exports: $Exports<'typography-theme-lincoln/dist/index'>;
}
declare module 'typography-theme-lincoln/src/index.js' {
  declare module.exports: $Exports<'typography-theme-lincoln/src/index'>;
}
